version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: qwerty  
    networks:
      - my-network

  app:
    image: nodejs24-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://root:qwerty@172.19.0.2:27017/nestdb 
    networks:
     - my-network

networks:
  my-network:
    driver: bridge
